### ISSUE TITLE
哥们哥们，域名咋回事🤔

### ISSUE THREAD

**Issue by antTing** [Pretend-to/mio-chat-nt#25]
你被黑了吗？我在上班，一点进去还好没人看见🌚

**Comment by Pretend-to** [comment]
十分抱歉，链接已经删掉了。那是我一年前在 namesilo 购买的域名，正常使用半年以后不知道为什么被 namesilo 封号，收回域名，转手卖给 H 。

**Comment by antTing** [comment]
哈哈他坑你，我也删掉这条吧
